
services:
  db:
    container_name: "project_db"
    image: postgres:12.0-alpine
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=pass
      - POSTGRES_DB=project
    ports:
      - "5432:5432"

